"""
LASA Handwriting Dataset Shapes
"""
# src/pyLASAHandwritingDataset/shapes.py

from typing import Literal

ShapeName = Literal[
    "Angle",
    "BendedLine",
    "CShape",
    "DoubleBendedLine",
    "GShape",
    "heee",
    "JShape_2",
    "JShape",
    "Khamesh",
    "Leaf_1",
    "Leaf_2",
    "Line",
    "LShape",
    "Multi_Models_1",
    "Multi_Models_2",
    "Multi_Models_3",
    "Multi_Models_4",
    "NShape",
    "PShape",
    "RShape",
    "Saeghe",
    "Sharpc",
    "Sine",
    "Snake",
    "Spoon",
    "Sshape",
    "Trapezoid",
    "Worm",
    "WShape",
    "Zshape",
]

ALL_SHAPES: tuple[ShapeName, ...] = (
    "Angle",
    "BendedLine",
    "CShape",
    "DoubleBendedLine",
    "GShape",
    "heee",
    "JShape_2",
    "JShape",
    "Khamesh",
    "Leaf_1",
    "Leaf_2",
    "Line",
    "LShape",
    "Multi_Models_1",
    "Multi_Models_2",
    "Multi_Models_3",
    "Multi_Models_4",
    "NShape",
    "PShape",
    "RShape",
    "Saeghe",
    "Sharpc",
    "Sine",
    "Snake",
    "Spoon",
    "Sshape",
    "Trapezoid",
    "Worm",
    "WShape",
    "Zshape",
)
